[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Create-test-cases-from-AtCoder-probrem"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["selenium"]

[project.scripts]
init = "src.initialize_environment:main"

[project.optional-dependencies]
dev = ["pytest", "pytest-randomly", "pytest-watch"]

[tool.hatch.build.targets.wheel]
packages = ["src"]
